// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model;
using Persistence;
using System;

namespace Persistence.Migrations
{
    [DbContext(typeof(CursosDbContext))]
    [Migration("20180321202047_inicia")]
    partial class inicia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.AlumnosPorCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completado");

                    b.Property<int>("CursoId");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("AlumnosPorCurso");
                });

            modelBuilder.Entity("Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Icon");

                    b.Property<string>("Nombre");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Imagen");

                    b.Property<string>("Nombre");

                    b.Property<decimal>("Precio");

                    b.Property<decimal>("Votos");

                    b.HasKey("Id");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Model.Ingresos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntidadId");

                    b.Property<int>("PagoCurso");

                    b.Property<int>("TipoIngreso");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("Model.LeccionesAprendidasPorUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LeccionId");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.ToTable("LeccionesAprendidasPorUsuario");
                });

            modelBuilder.Entity("Model.LeccionPorCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contenido");

                    b.Property<int>("CursoId");

                    b.Property<string>("Nombre");

                    b.Property<string>("Video");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("LeccionPorCurso");
                });

            modelBuilder.Entity("Model.RevisionCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comentario");

                    b.Property<int>("CursoId");

                    b.Property<decimal>("Voto");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("RevisionCurso");
                });

            modelBuilder.Entity("Model.AlumnosPorCurso", b =>
                {
                    b.HasOne("Model.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.LeccionesAprendidasPorUsuario", b =>
                {
                    b.HasOne("Model.LeccionPorCurso", "leccion")
                        .WithMany()
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.LeccionPorCurso", b =>
                {
                    b.HasOne("Model.Curso", "Curso")
                        .WithMany("Leccion")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.RevisionCurso", b =>
                {
                    b.HasOne("Model.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
